Resources:
  ################
  # Setup Caching
  ################
  # ApiGatewayStage:
  #   Type: "AWS::ApiGateway::Stage"
  #   Properties:
      # CacheClusterEnabled: true
      # CacheClusterSize: "1.6"
      # DeploymentId:
      #   Ref: __deployment__
      # RestApiId:
      #   Ref: ApiGatewayRestApi
      # StageName : ${self:provider.stage}
      # MethodSettings:
      #   - ResourcePath: "/*"
      #     HttpMethod: "*"
      #     CachingEnabled: false
      #   - ResourcePath: /api~1booli~1sold
      #     HttpMethod: "*"
      #     CacheDataEncrypted: true
      #     CacheTtlInSeconds: 300 #${self:provider.environment.API_GATEWAY_CACHE_TTL}
      #     CachingEnabled: true
      #   - ResourcePath: /api~1google-distance~1areas
      #     HttpMethod: "*"
      #     CacheDataEncrypted: true
      #     CacheTtlInSeconds: 300 #${self:provider.environment.API_GATEWAY_CACHE_TTL}
      #     CachingEnabled: true
  #####################
  # End of cache setup
  #####################

  ##################################
  # Start of /api/google-distance*
  ##################################
  ApiGatewayResourceApiGoogledistance:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - "ApiGatewayRestApi"
          - "RootResourceId"
      PathPart: 'google-distance'
      RestApiId:
        Ref: ApiGatewayRestApi
  ApiGatewayMethodApiGoogledistance:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: ApiGatewayResourceApiGoogledistance
      RestApiId:
        Ref: ApiGatewayRestApi
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: GET
        Type: HTTP_PROXY
        Uri: ${self:custom.EBBackendUrl}/api/google-distance/ # the URL you want to set a proxy to
        PassthroughBehavior: WHEN_NO_MATCH
  ApiGatewayResourceApiGoogledistanceAreas:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Ref: ApiGatewayResourceApiGoogledistance
      PathPart: 'areas'
      RestApiId:
        Ref: ApiGatewayRestApi
  ApiGatewayMethodApiGoogledistanceAreas:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: ApiGatewayResourceApiGoogledistanceAreas
      RestApiId:
        Ref: ApiGatewayRestApi
      AuthorizationType: NONE
      HttpMethod: ANY # the method of your proxy. Is it GET or POST or ... ?
      RequestParameters:
        method.request.querystring.digest: true
      Integration:
        IntegrationHttpMethod: ANY
        Type: HTTP_PROXY
        Uri: ${self:custom.EBBackendUrl}/api/google-distance/areas # the URL you want to set a proxy to
        CacheKeyParameters:
          - method.request.querystring.digest
        PassthroughBehavior: WHEN_NO_MATCH
  ###############################
  # end of /api/google-distance*
  ###############################

  #######################################
  # Start of /api/google-places-destination*
  #######################################
  ApiGatewayResourceApiGoogleplacesdestination:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - "ApiGatewayRestApi"
          - "RootResourceId"
      PathPart: 'google-places-destination'
      RestApiId:
        Ref: ApiGatewayRestApi
  ApiGatewayResourceApiGoogleplacesdestinationProxyMethodPost:
    Type: AWS::ApiGateway::Method
    Properties:
      ResourceId:
        Ref: ApiGatewayResourceApiGoogleplacesdestination
      RestApiId:
        Ref: ApiGatewayRestApi
      AuthorizationType: NONE
      HttpMethod: POST # the method of your proxy. Is it GET or POST or ... ?
      RequestParameters:
        method.request.querystring.digest: true
      Integration:
        IntegrationHttpMethod: POST
        Type: HTTP_PROXY
        Uri: ${self:custom.EBBackendUrl}/api/google-places-destination # the URL you want to set a proxy to
        CacheKeyParameters:
          - method.request.querystring.digest
        PassthroughBehavior: WHEN_NO_MATCH
  ####################################
  # End of /api/google-places-destination
  ####################################
